version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/node_modules:/app/node_modules 
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/COMP3123-Assignment
    networks:
      - app-network

  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

networks:
  app-network:

volumes:
  mongo-data:
